export const OYO_STATES = [
  { value: "afijio", label: "Afijio" },
  { value: "akinyele", label: "Akinyele" },
  { value: "atiba", label: "Atiba" },
  { value: "atisbo", label: "Atisbo" },
  { value: "egbeda", label: "Egbeda" },
  { value: "ibadan north", label: "Ibadan North" },
  { value: "ibadan north-east", label: "Ibadan North-East" },
  { value: "ibadan north west", label: "Ibadan North West" },
  { value: "ibadan south-east", label: "Ibadan South-East" },
  { value: "ibadan south west", label: "Ibadan South West" },
  { value: "ibarapa central", label: "Ibarapa Central" },
  { value: "ibarapa east", label: "Ibarapa East" },
  { value: "ibarapa north", label: "Ibarapa North" },
  { value: "ido", label: "Ido" },
  { value: "irepo", label: "Irepo" },
  { value: "iseyin", label: "Iseyin" },
  { value: "itesiwaju", label: "Itesiwaju" },
  { value: "iwajowa", label: "Iwajowa" },
  { value: "kajola", label: "Kajola" },
  { value: "lagelu", label: "Lagelu" },
  { value: "ogbomoso north", label: "Ogbomoso North" },
  { value: "ogbomosho south", label: "Ogbomosho South" },
  { value: "ogo oluwa", label: "Ogo Oluwa" },
  { value: "olorunsogo", label: "Olorunsogo" },
  { value: "oluyole", label: "Oluyole" },
  { value: "ona ara", label: "Ona Ara" },
  { value: "orelope", label: "Orelope" },
  { value: "oriire", label: "Oriire" },
  { value: "oyo east", label: "Oyo East" },
  { value: "oyo west", label: "Oyo West" },
  { value: "saki east", label: "Saki East" },
  { value: "saki west", label: "Saki West" },
  { value: "surulere", label: "Surulere" },
];
